### ISSUE TITLE
Forward `kghub.io` to KG-Hub URLs

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/knowledge-graph-hub-support#4]
KG-Hub projects and their files are currently hosted on an S3 bucket served through Cloudflare.
The Cloudflare site is accessed through https://kg-hub.berkeleybop.io/ .
We would like to use `kghub.io` instead, but would like the existing URLs to work or we risk breaking KG-Hub into very small non-working pieces.

For example:

- https://kghub.io/ should forward to https://kg-hub.berkeleybop.io/
- https://kghub.io/kg-phenio/current/ should forward to https://kg-hub.berkeleybop.io/kg-phenio/current/
- https://kghub.io/kg-idg/20230101/stats/merged_graph_stats.yaml should forward to https://kg-hub.berkeleybop.io/kg-idg/20230101/stats/merged_graph_stats.yaml
- https://kghub.io/kg-obo/bfo/2019-08-26/kg-obo_version should forward to https://kg-hub.berkeleybop.io/kg-obo/bfo/2019-08-26/kg-obo_version

The idea here is that we will switch to the new URLs at a future point.

@kltm

**Comment by kltm** [comment]
@caufieldjh Okay, there is an additional complication here: to go from https, we'll need to get a cert for the originating domain. I think I can set that up pretty easily; likely I'd setup on the build machine for convenience.

**Comment by kltm** [comment]
kghub.io now A record to same machine as build.berkeleybop.io.
Working on cert and forwarding proxy next.

**Comment by kltm** [comment]
Cert has been acquired using the same questionable/brittle process that I use for build.berkeleybop.io.

**Comment by kltm** [comment]
@caufieldjh I believe this is ready for testing. (I have not yet archived the confs.)

**Comment by kltm** [comment]
Noting that the additional continuing overhead for this, given that we're already running build.berkeleybop.io, is doing the occasional (once every three months) manual cert renewal SOP for kghub.io. This will end once these become the core URLs (supported by DNS) and the forwarding proxy can be taken down.
